# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink: "/:title/"

highlighter: pygments

timezone: Asia/Kolkata

# Default YAML frontmatter settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true

# Tagging settings
tag_title_prefix:   "Posts tagged #"
tag_title_suffix:   ""

# Image settings
image_base:          /public/images/

# Do not copy these file to the output directory
exclude: ["transfer.sh", README.md, setup.sh]

# Setup
title:               Democracy India
tagline:             Revive democracy in India
url:                 "http://democracy-india.github.io"
paginate_l:           4
baseurl:             "/x"

paginate_langs:      ["en"]

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Vivek Jhangra
  email:             rainy.algorithm@protonmail.com

# Custom vars
version:             1.0.0
github:
  repo:              https://github.com/democracy-india/democracy-india.github.io

# Google sitemap generation
plugins:
  - jekyll-sitemap
  - jekyll-paginate

# Conversion
markdown:    redcarpet
excerpt_separator: "<!--break-->"

redcarpet:
  extensions: ["footnotes", "tables", "autolink"]

kramdown:
  auto_ids: true

pages_list:
  Tags: '/x/tags'
  Feed: '/x/atom.xml'

picture:
  source: "_assets/imgs/_fullsize"
  output: "generated"
  markup: "picture"
  presets:
    default:
      ppi: [1, 1.5, 2]
      source_medium:
        media: "(min-width: 40em)"
        width: "640"
      source_small:
        height: "100"
      source_default:
        width: "640"
